import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { Compass, TriangleAlert } from "lucide-react";
import { Section } from "@/components/layout/Section";
import { Card } from "@/components/ui/Card";
import { LinkButton } from "@/components/ui/Button";
import { GuidanceNotice } from "@/components/ui/GuidanceNotice";
import { RecommendationCard } from "@/components/sections/recommendations/RecommendationCard";
import { getStudentProfileSnapshot } from "@/lib/supabase/student-profile";
import { getCareersForMatching } from "@/lib/supabase/careers";
import { getRecommendations, hasMinimumProfileDataForRecommendations } from "@/lib/recommendations";

export const metadata: Metadata = {
  title: "Career Recommendations",
  description: "Careers ranked against your Student Digital Profile, with plain-language reasons for each match.",
};

/**
 * Milestone 5 — the real, personalised recommendation experience.
 *
 * Protected via `PROTECTED_PATHS` in `src/lib/supabase/middleware.ts` (the
 * `redirect` below is defense in depth, matching the pattern used on
 * `/profile`). Every ranking is computed fresh on each load from the
 * signed-in student's own `student_*` rows (RLS-scoped to `auth.uid()`)
 * and the current approved career catalogue — nothing is persisted, so
 * results can never go stale, and there is no way for this page to read
 * another student's data.
 *
 * This engine is a structured decision-support tool, not a psychometric
 * assessment or an AI system — see the disclaimer below and
 * docs/recommendation-engine-guide.md for the full model write-up.
 */
export default async function RecommendationsPage() {
  const snapshot = await getStudentProfileSnapshot();
  if (!snapshot) redirect("/login?next=/recommendations");

  if (!hasMinimumProfileDataForRecommendations(snapshot)) {
    return (
      <Section tone="muted" className="pt-10 sm:pt-14">
        <PageIntro />
        <Card className="mt-8 flex flex-col items-center gap-3 py-14 text-center">
          <Compass aria-hidden="true" className="h-10 w-10 text-muted" />
          <h2 className="text-lg font-semibold text-primary">Your profile needs a bit more first</h2>
          <p className="max-w-md text-sm text-muted">
            Recommendations compare your Student Digital Profile against our career library — the more of it you
            fill in, the more useful and reliable your results will be. Add at least a couple of subject strengths,
            interests, or skills to get started.
          </p>
          <LinkButton href="/profile/onboarding" className="mt-2">
            Continue your profile
          </LinkButton>
        </Card>
      </Section>
    );
  }

  const careers = await getCareersForMatching();

  if (careers.length === 0) {
    return (
      <Section tone="muted" className="pt-10 sm:pt-14">
        <PageIntro />
        <Card className="mt-8 flex flex-col items-center gap-3 py-14 text-center">
          <TriangleAlert aria-hidden="true" className="h-10 w-10 text-muted" />
          <h2 className="text-lg font-semibold text-primary">Recommendations aren&apos;t available right now</h2>
          <p className="max-w-md text-sm text-muted">
            We couldn&apos;t load the career library just now. Please try again in a moment — your profile data is
            safe and nothing here depends on it.
          </p>
        </Card>
      </Section>
    );
  }

  const { results, totalCareersConsidered } = getRecommendations(snapshot, careers);

  return (
    <Section tone="muted" className="pt-10 sm:pt-14">
      <PageIntro />

      <p className="mt-6 text-sm text-muted">
        Compared against {totalCareersConsidered} career{totalCareersConsidered === 1 ? "" : "s"} in our library —
        showing your top {results.length}.
      </p>

      <div className="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        {results.map((result) => (
          <RecommendationCard key={result.careerId} result={result} />
        ))}
      </div>

      <GuidanceNotice className="mt-8">
        These are structured, rules-based comparisons against the profile you&apos;ve entered — not a scientifically
        validated psychometric assessment, and not generated by an AI model. Results depend entirely on the
        information you&apos;ve provided so far, and your interests, skills, and priorities can change — a
        lower-ranked career isn&apos;t automatically unsuitable, it&apos;s just less evidenced right now. Salary,
        outlook, and other career details are curated heuristics, not guarantees. Use this as a starting point for
        exploring options, not a final decision.
      </GuidanceNotice>
    </Section>
  );
}

function PageIntro() {
  return (
    <div className="mb-2">
      <p className="text-sm font-semibold uppercase tracking-wide text-secondary">Recommendations</p>
      <h1 className="mt-2 text-3xl font-semibold text-primary balance sm:text-4xl">Careers worth exploring</h1>
      <p className="mt-2 max-w-2xl text-muted">
        Ranked against your Student Digital Profile — subjects, interests, skills, work preferences, and priorities
        — with plain-language reasons for each one.
      </p>
    </div>
  );
}
