/**
 * Milestone 4 career seed SQL generator.
 *
 * Run with: npm run seed:generate
 *
 * Reads the TypeScript seed data (src/data/careers/index.ts + taxonomy.ts)
 * and writes a single idempotent SQL file to
 * `supabase/seed/0001_careers_seed.sql`. That file is safe to paste into
 * the Supabase SQL Editor and run — once, or many times:
 *
 *  - career_families / industries / career_tags / careers are written with
 *    `insert ... on conflict (<stable key>) do update` — re-running updates
 *    existing rows in place rather than duplicating them.
 *  - every child table (subject/interest/skill requirements, work
 *    preference profile, career priority profile, education routes,
 *    career_industries, career_tag_map, career_aliases, career_related) is
 *    written as `delete rows for these career_ids` followed by a fresh
 *    `insert` — this is the same delete-then-insert pattern used for
 *    Milestone 3 student data, and it means edits or removals in the
 *    TypeScript seed file are correctly reflected on the next seed run
 *    instead of leaving stale rows behind.
 *
 * This script does not connect to Supabase — it only reads local
 * TypeScript files and writes a local .sql file. Always run
 * `npm run validate:careers` first; this generator does not re-validate.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";

import { ALL_CAREERS, CAREER_FAMILIES } from "../src/data/careers/index";
import { INDUSTRY_OPTIONS, CAREER_TAG_OPTIONS } from "../src/data/careers/taxonomy";
import type { CareerSeed } from "../src/data/careers/taxonomy";

const OUT_PATH = join(__dirname, "..", "supabase", "seed", "0001_careers_seed.sql");

// ---------------------------------------------------------------------------
// SQL literal helpers
// ---------------------------------------------------------------------------
function str(v: string | undefined | null): string {
  if (v === undefined || v === null) return "null";

  // Dollar-quoted literals keep long prose opaque to PostgreSQL's lexer and
  // avoid relying on apostrophe/backslash handling in copied SQL. Choose a
  // delimiter that cannot collide with the value itself.
  let tag = "seed";
  while (v.includes(`$${tag}$`)) tag += "_";
  return `$${tag}$${v}$${tag}$`;
}
function num(v: number | undefined | null): string {
  if (v === undefined || v === null) return "null";
  return String(v);
}
function bool(v: boolean | undefined): string {
  return v ? "true" : "false";
}

const lines: string[] = [];
function emit(s: string) {
  lines.push(s);
}

emit(`-- ============================================================================`);
emit(`-- Milestone 4 — Career Knowledge Base seed data (GENERATED FILE)`);
emit(`--`);
emit(`-- Generated by scripts/generate-career-seed-sql.ts from src/data/careers/*.ts.`);
emit(`-- Do NOT hand-edit this file — edit the TypeScript seed data and re-run:`);
emit(`--   npm run validate:careers   (fails loudly on any bad/unknown key)`);
emit(`--   npm run seed:generate      (regenerates this file)`);
emit(`--`);
emit(`-- HOW TO RUN THIS (no SQL knowledge required):`);
emit(`--   1. First run supabase/migrations/0003_career_database.sql (once) if`);
emit(`--      you haven't already — this seed file assumes those tables exist.`);
emit(`--   2. Open your Supabase project dashboard (supabase.com/dashboard).`);
emit(`--   3. Click "SQL Editor" in the left sidebar, then "New query".`);
emit(`--   4. Paste the entire contents of this file.`);
emit(`--   5. Click "Run".`);
emit(`--`);
emit(`-- Safe to run more than once — every statement below is an upsert or a`);
emit(`-- delete-then-insert keyed off a stable business key (family_key,`);
emit(`-- industry_key, tag_key, career_key), never a raw INSERT. Re-running this`);
emit(`-- file after editing the TypeScript seed data updates existing rows in`);
emit(`-- place instead of creating duplicates.`);
emit(`-- ============================================================================`);
emit("");

// ---------------------------------------------------------------------------
// 1. career_families
// ---------------------------------------------------------------------------
emit(`-- ----------------------------------------------------------------------------`);
emit(`-- 1. career_families`);
emit(`-- ----------------------------------------------------------------------------`);
emit(`insert into public.career_families (family_key, name, description, display_order, is_active)`);
emit(`values`);
emit(
  CAREER_FAMILIES.map(
    (f, i) =>
      `  (${str(f.key)}, ${str(f.name)}, ${str(f.description)}, ${num(f.order)}, true)${
        i === CAREER_FAMILIES.length - 1 ? "" : ","
      }`
  ).join("\n")
);
emit(`on conflict (family_key) do update set`);
emit(`  name = excluded.name,`);
emit(`  description = excluded.description,`);
emit(`  display_order = excluded.display_order,`);
emit(`  is_active = excluded.is_active,`);
emit(`  updated_at = now();`);
emit("");

// ---------------------------------------------------------------------------
// 2. industries
// ---------------------------------------------------------------------------
emit(`-- ----------------------------------------------------------------------------`);
emit(`-- 2. industries`);
emit(`-- ----------------------------------------------------------------------------`);
emit(`insert into public.industries (industry_key, name, display_order, is_active)`);
emit(`values`);
emit(
  INDUSTRY_OPTIONS.map(
    (ind, i) => `  (${str(ind.key)}, ${str(ind.label)}, ${num(i * 10)}, true)${i === INDUSTRY_OPTIONS.length - 1 ? "" : ","}`
  ).join("\n")
);
emit(`on conflict (industry_key) do update set`);
emit(`  name = excluded.name,`);
emit(`  display_order = excluded.display_order,`);
emit(`  is_active = excluded.is_active,`);
emit(`  updated_at = now();`);
emit("");

// ---------------------------------------------------------------------------
// 3. career_tags
// ---------------------------------------------------------------------------
emit(`-- ----------------------------------------------------------------------------`);
emit(`-- 3. career_tags`);
emit(`-- ----------------------------------------------------------------------------`);
emit(`insert into public.career_tags (tag_key, label)`);
emit(`values`);
emit(
  CAREER_TAG_OPTIONS.map(
    (t, i) => `  (${str(t.key)}, ${str(t.label)})${i === CAREER_TAG_OPTIONS.length - 1 ? "" : ","}`
  ).join("\n")
);
emit(`on conflict (tag_key) do update set`);
emit(`  label = excluded.label;`);
emit("");

// ---------------------------------------------------------------------------
// 4. careers (core record) — joins to career_families on family_key
// ---------------------------------------------------------------------------
emit(`-- ----------------------------------------------------------------------------`);
emit(`-- 4. careers`);
emit(`-- ----------------------------------------------------------------------------`);
emit(`insert into public.careers (`);
emit(`  career_key, family_id, title, short_title, slug, summary, what_you_do,`);
emit(`  typical_environment, career_outlook_summary, typical_entry_level, minimum_education_key,`);
emit(`  international_mobility_score, remote_work_score, entrepreneurship_score, salary_potential_score,`);
emit(`  job_security_score, creativity_score, social_impact_score, leadership_opportunity_score,`);
emit(`  travel_score, research_intensity_score, technical_depth_score,`);
emit(`  is_active, is_featured, data_quality_status`);
emit(`)`);
emit(`select`);
emit(`  v.career_key, f.id, v.title, v.short_title, v.slug, v.summary, v.what_you_do,`);
emit(`  v.typical_environment, v.career_outlook_summary, v.typical_entry_level, v.minimum_education_key,`);
emit(`  v.international_mobility_score, v.remote_work_score, v.entrepreneurship_score, v.salary_potential_score,`);
emit(`  v.job_security_score, v.creativity_score, v.social_impact_score, v.leadership_opportunity_score,`);
emit(`  v.travel_score, v.research_intensity_score, v.technical_depth_score,`);
emit(`  true, v.is_featured, v.data_quality_status`);
emit(`from (values`);
emit(
  ALL_CAREERS.map((c, i) => {
    const s = c.scores ?? {};
    const row = [
      str(c.careerKey),
      str(c.familyKey),
      str(c.title),
      str(c.shortTitle),
      str(c.slug),
      str(c.summary),
      str(c.whatYouDo),
      str(c.typicalEnvironment),
      str(c.careerOutlookSummary),
      str(c.typicalEntryLevel),
      str(c.minimumEducationKey),
      num(s.internationalMobility),
      num(s.remoteWork),
      num(s.entrepreneurship),
      num(s.salaryPotential),
      num(s.jobSecurity),
      num(s.creativity),
      num(s.socialImpact),
      num(s.leadershipOpportunity),
      num(s.travel),
      num(s.researchIntensity),
      num(s.technicalDepth),
      bool(c.isFeatured),
      str(c.dataQualityStatus),
    ];
    return `  (${row.join(", ")})${i === ALL_CAREERS.length - 1 ? "" : ","}`;
  }).join("\n")
);
emit(`) as v(`);
emit(`  career_key, family_key, title, short_title, slug, summary, what_you_do,`);
emit(`  typical_environment, career_outlook_summary, typical_entry_level, minimum_education_key,`);
emit(`  international_mobility_score, remote_work_score, entrepreneurship_score, salary_potential_score,`);
emit(`  job_security_score, creativity_score, social_impact_score, leadership_opportunity_score,`);
emit(`  travel_score, research_intensity_score, technical_depth_score,`);
emit(`  is_featured, data_quality_status`);
emit(`)`);
emit(`join public.career_families f on f.family_key = v.family_key`);
emit(`on conflict (career_key) do update set`);
emit(`  family_id = excluded.family_id,`);
emit(`  title = excluded.title,`);
emit(`  short_title = excluded.short_title,`);
emit(`  slug = excluded.slug,`);
emit(`  summary = excluded.summary,`);
emit(`  what_you_do = excluded.what_you_do,`);
emit(`  typical_environment = excluded.typical_environment,`);
emit(`  career_outlook_summary = excluded.career_outlook_summary,`);
emit(`  typical_entry_level = excluded.typical_entry_level,`);
emit(`  minimum_education_key = excluded.minimum_education_key,`);
emit(`  international_mobility_score = excluded.international_mobility_score,`);
emit(`  remote_work_score = excluded.remote_work_score,`);
emit(`  entrepreneurship_score = excluded.entrepreneurship_score,`);
emit(`  salary_potential_score = excluded.salary_potential_score,`);
emit(`  job_security_score = excluded.job_security_score,`);
emit(`  creativity_score = excluded.creativity_score,`);
emit(`  social_impact_score = excluded.social_impact_score,`);
emit(`  leadership_opportunity_score = excluded.leadership_opportunity_score,`);
emit(`  travel_score = excluded.travel_score,`);
emit(`  research_intensity_score = excluded.research_intensity_score,`);
emit(`  technical_depth_score = excluded.technical_depth_score,`);
emit(`  is_active = true,`);
emit(`  is_featured = excluded.is_featured,`);
emit(`  data_quality_status = excluded.data_quality_status,`);
emit(`  updated_at = now();`);
emit("");

// ---------------------------------------------------------------------------
// Generic helper: delete-then-insert a child table keyed by career_key,
// joined to public.careers on career_key to resolve career_id.
// ---------------------------------------------------------------------------
const allCareerKeysList = ALL_CAREERS.map((c) => str(c.careerKey)).join(", ");

function emitChildTable(opts: {
  sectionTitle: string;
  table: string;
  valueColumns: string[]; // columns after career_key, in VALUES order
  insertColumns: string[]; // destination columns (career_id first, then these)
  rows: (c: CareerSeed) => string[][]; // each inner array = one VALUES row's non-career_key columns (already SQL-literal strings)
}) {
  const { sectionTitle, table, valueColumns, insertColumns, rows } = opts;
  emit(`-- ----------------------------------------------------------------------------`);
  emit(`-- ${sectionTitle}`);
  emit(`-- ----------------------------------------------------------------------------`);
  emit(`delete from public.${table}`);
  emit(`where career_id in (select id from public.careers where career_key in (${allCareerKeysList}));`);
  emit("");

  const allRows: string[] = [];
  for (const c of ALL_CAREERS) {
    for (const r of rows(c)) {
      allRows.push(`  (${str(c.careerKey)}, ${r.join(", ")})`);
    }
  }

  if (allRows.length === 0) {
    emit(`-- (no rows to insert for ${table})`);
    emit("");
    return;
  }

  emit(`insert into public.${table} (${insertColumns.join(", ")})`);
  emit(`select c.id, ${valueColumns.map((col) => `v.${col}`).join(", ")}`);
  emit(`from (values`);
  emit(allRows.join(",\n"));
  emit(`) as v(career_key, ${valueColumns.join(", ")})`);
  emit(`join public.careers c on c.career_key = v.career_key;`);
  emit("");
}

// 5. career_subject_requirements
emitChildTable({
  sectionTitle: "5. career_subject_requirements",
  table: "career_subject_requirements",
  valueColumns: ["subject_key", "importance", "minimum_strength"],
  insertColumns: ["career_id", "subject_key", "importance", "minimum_strength"],
  rows: (c) => (c.subjects ?? []).map((s) => [str(s.subjectKey), num(s.importance), num(s.minimumStrength)]),
});

// 6. career_interest_requirements
emitChildTable({
  sectionTitle: "6. career_interest_requirements",
  table: "career_interest_requirements",
  valueColumns: ["interest_key", "importance"],
  insertColumns: ["career_id", "interest_key", "importance"],
  rows: (c) => (c.interests ?? []).map((s) => [str(s.interestKey), num(s.importance)]),
});

// 7. career_skill_requirements
emitChildTable({
  sectionTitle: "7. career_skill_requirements",
  table: "career_skill_requirements",
  valueColumns: ["skill_key", "importance", "recommended_level"],
  insertColumns: ["career_id", "skill_key", "importance", "recommended_level"],
  rows: (c) => (c.skills ?? []).map((s) => [str(s.skillKey), num(s.importance), str(s.recommendedLevel)]),
});

// 8. career_work_preference_profile
emitChildTable({
  sectionTitle: "8. career_work_preference_profile",
  table: "career_work_preference_profile",
  valueColumns: ["preference_key", "score"],
  insertColumns: ["career_id", "preference_key", "score"],
  rows: (c) => (c.workPreferences ?? []).map((s) => [str(s.preferenceKey), num(s.score)]),
});

// 9. career_priority_profile
emitChildTable({
  sectionTitle: "9. career_priority_profile",
  table: "career_priority_profile",
  valueColumns: ["priority_key", "score"],
  insertColumns: ["career_id", "priority_key", "score"],
  rows: (c) => (c.careerPriorities ?? []).map((s) => [str(s.priorityKey), num(s.score)]),
});

// 10. career_education_routes
emitChildTable({
  sectionTitle: "10. career_education_routes",
  table: "career_education_routes",
  valueColumns: ["education_level", "field_key", "specialization_key", "relevance", "notes"],
  insertColumns: ["career_id", "education_level", "field_key", "specialization_key", "relevance", "notes"],
  rows: (c) =>
    (c.educationRoutes ?? []).map((r) => [
      str(r.educationLevel),
      str(r.fieldKey),
      str(r.specializationKey),
      str(r.relevance),
      str(r.notes),
    ]),
});

// 11. career_aliases
emitChildTable({
  sectionTitle: "11. career_aliases",
  table: "career_aliases",
  valueColumns: ["alias", "normalized_alias"],
  insertColumns: ["career_id", "alias", "normalized_alias"],
  rows: (c) => (c.aliases ?? []).map((a) => [str(a), str(a.trim().toLowerCase())]),
});

// ---------------------------------------------------------------------------
// 12. career_industries — join target is industries, not careers, so use a
// bespoke (not the generic single-join) statement.
// ---------------------------------------------------------------------------
{
  emit(`-- ----------------------------------------------------------------------------`);
  emit(`-- 12. career_industries`);
  emit(`-- ----------------------------------------------------------------------------`);
  emit(`delete from public.career_industries`);
  emit(`where career_id in (select id from public.careers where career_key in (${allCareerKeysList}));`);
  emit("");

  const rows: string[] = [];
  for (const c of ALL_CAREERS) {
    for (const industryKey of c.industryKeys ?? []) {
      rows.push(`  (${str(c.careerKey)}, ${str(industryKey)})`);
    }
  }

  if (rows.length > 0) {
    emit(`insert into public.career_industries (career_id, industry_id)`);
    emit(`select c.id, ind.id`);
    emit(`from (values`);
    emit(rows.join(",\n"));
    emit(`) as v(career_key, industry_key)`);
    emit(`join public.careers c on c.career_key = v.career_key`);
    emit(`join public.industries ind on ind.industry_key = v.industry_key;`);
  } else {
    emit(`-- (no rows to insert for career_industries)`);
  }
  emit("");
}

// ---------------------------------------------------------------------------
// 13. career_tag_map — join target is career_tags.
// ---------------------------------------------------------------------------
{
  emit(`-- ----------------------------------------------------------------------------`);
  emit(`-- 13. career_tag_map`);
  emit(`-- ----------------------------------------------------------------------------`);
  emit(`delete from public.career_tag_map`);
  emit(`where career_id in (select id from public.careers where career_key in (${allCareerKeysList}));`);
  emit("");

  const rows: string[] = [];
  for (const c of ALL_CAREERS) {
    for (const tagKey of c.tagKeys ?? []) {
      rows.push(`  (${str(c.careerKey)}, ${str(tagKey)})`);
    }
  }

  if (rows.length > 0) {
    emit(`insert into public.career_tag_map (career_id, tag_id)`);
    emit(`select c.id, t.id`);
    emit(`from (values`);
    emit(rows.join(",\n"));
    emit(`) as v(career_key, tag_key)`);
    emit(`join public.careers c on c.career_key = v.career_key`);
    emit(`join public.career_tags t on t.tag_key = v.tag_key;`);
  } else {
    emit(`-- (no rows to insert for career_tag_map)`);
  }
  emit("");
}

// ---------------------------------------------------------------------------
// 14. career_related — manual curation only (relatedCareerKeys). Both
// endpoints resolve against public.careers via career_key.
// ---------------------------------------------------------------------------
{
  emit(`-- ----------------------------------------------------------------------------`);
  emit(`-- 14. career_related (manually curated — relatedCareerKeys)`);
  emit(`-- ----------------------------------------------------------------------------`);
  emit(`delete from public.career_related`);
  emit(`where career_id in (select id from public.careers where career_key in (${allCareerKeysList}));`);
  emit("");

  const rows: string[] = [];
  for (const c of ALL_CAREERS) {
    (c.relatedCareerKeys ?? []).forEach((rk, i) => {
      rows.push(`  (${str(c.careerKey)}, ${str(rk)}, ${num(i * 10)})`);
    });
  }

  if (rows.length > 0) {
    emit(`insert into public.career_related (career_id, related_career_id, display_order)`);
    emit(`select c.id, rc.id, v.display_order`);
    emit(`from (values`);
    emit(rows.join(",\n"));
    emit(`) as v(career_key, related_career_key, display_order)`);
    emit(`join public.careers c on c.career_key = v.career_key`);
    emit(`join public.careers rc on rc.career_key = v.related_career_key;`);
  } else {
    emit(`-- (no rows to insert for career_related)`);
  }
  emit("");
}

emit(`-- ============================================================================`);
emit(`-- Done. ${ALL_CAREERS.length} careers across ${CAREER_FAMILIES.length} families seeded/updated.`);
emit(`-- ============================================================================`);

// ---------------------------------------------------------------------------
// Write file
// ---------------------------------------------------------------------------
mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, lines.join("\n") + "\n", "utf8");

console.log(`Wrote ${OUT_PATH}`);
console.log(`  ${ALL_CAREERS.length} careers, ${CAREER_FAMILIES.length} families, ${INDUSTRY_OPTIONS.length} industries, ${CAREER_TAG_OPTIONS.length} tags`);
